Feature/bm 111 implement auth interceptor
bingemate/frontend pull request #127
Opened 2023-04-26 19:43 UTC by pooetitu

2023-04-26 20:33 UTC, Nouuu requested changes
Un tout petit truc à changer sur le nom de l'entête, sinon nickel !

2023-04-26 20:33 UTC, Nouuu commented on src/app/core/http-interceptors/auth-http.interceptor.ts
> +      headers = headers.set('user-id', userId);
Met le en `User-Id`, pour être sûr

2023-04-26 20:33 UTC, Nouuu commented on src/app/core/http-interceptors/auth-http.interceptor.ts
> +    const userId = this.store.selectSnapshot(AuthState.user)?.id;
👍

2023-04-26 20:33 UTC, Nouuu commented on src/app/core/core.module.ts
> +    ],
Lourd.
En vrai ça vaaaaa

2023-04-27 18:00 UTC, pooetitu commented on src/app/core/http-interceptors/auth-http.interceptor.ts
> +      headers = headers.set('user-id', userId);
Le nom du header n'est pas case sensitive j'ai check

2023-04-27 18:02 UTC, Nouuu commented on src/app/core/http-interceptors/auth-http.interceptor.ts
> +      headers = headers.set('user-id', userId);
ok tout cool !

2023-04-27 18:02 UTC, Nouuu approved these changes

2023-04-28 16:45 UTC, merged